# -*- coding: utf-8 -*-
"""Palindrone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHd8F6i6dK0gbUFPDD3JMqJuVcakJG6p
"""

def is_palindrone(string):
    reverseString = string[::-1]
    return string == reverseString

word = 'madam'
if is_palindrone(word):
  print(f"{word} is a palindrone")
else:
  print(f"{word} is not a palindrone")